# Generated by Django 3.1.7 on 2021-03-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210325_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='name',
            field=models.CharField(default='scenario name', max_length=100),
            preserve_default=False,
        ),
    ]
