# Generated by Django 3.1.7 on 2021-03-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210314_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqoption',
            old_name='options',
            new_name='option',
        ),
    ]
