# Generated by Django 3.1.7 on 2021-03-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210327_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='course_id',
        ),
        migrations.CreateModel(
            name='StudentsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.courses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
    ]
