version: "3"
services:
  frontend-editor:
    build:
      context: editor/frontend/ethisim
    ports:
      - 3000:80
    depends_on:
      - backend-editor
    volumes:
      - ./editor/frontend/ethisim:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: frontend-editor
    networks:
      - '320'

  frontend-simulator:
    build:
      context: simulator/frontend
    ports:
      - 3001:80
    depends_on:
      - backend-simulator
    volumes:
      - ./simulator/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: frontend-simulator
    networks:
      - '320'

  frontend-landing-page:
    build:
      context: landing page/welcome-login
    ports:
      - 3006:80
    volumes:
      - ./landing page/welcome-login:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: frontend-landing-page
    networks:
      - '320'
  
  backend-simulator:
    build:
      context: simulator/steminist_simulator_backend
    ports:
      - 7000:8000
    depends_on:
      - database
    environment:
      - PGHOST=${POSTGRESHOST}
      - PGUSER=${POSTGRESUSERNAME}
      - PGPASSWORD=${POSTGRESPASSWORD}
      - PGDATABASE=${POSTGRESDB}
      - PGPORT=5432
    networks:
      - '320'
    container_name: backend-simulator

  backend-editor:
    build:
      context: editor/backend
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - POSTGRESHOST=${POSTGRESHOST}
      - POSTGRESUSERNAME=${POSTGRESUSERNAME}
      - POSTGRESPASSWORD=${POSTGRESPASSWORD}
      - POSTGRESDB=${POSTGRESDB}
    networks:
      - '320'
    container_name: backend-editor

  database:
    image: postgres
    container_name: postgres-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=db"
    ports:
      - 5432:5432
    expose:
      - '5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - '320'

volumes:
  postgres-data:

networks:
  '320':
