version: "3"
services:
  frontend-editor:
    image: dacollins/docking:frontend-editor
    ports:
      - 3000:80
    depends_on:
      - backend-editor
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: frontend-editor
    networks:
      - '320'

  frontend-simulator:
    image: dacollins/docking:frontend-simulator
    ports:
      - 3001:80
    depends_on:
      - backend-simulator
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: frontend-simulator
    networks:
      - '320'

  frontend-landing-page:
    image: dacollins/docking:frontend-landing-page
    ports:
      - 3006:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: frontend-landing-page
    networks:
      - '320'
  
  backend-simulator:
    image: dacollins/docking:backend-simulator
    ports:
      - 5000:5000
    depends_on:
      - database
    environment:
      - PGHOST=${POSTGRESHOST}
      - PGUSER=${POSTGRESUSERNAME}
      - PGPASSWORD=${POSTGRESPASSWORD}
      - PGDATABASE=${POSTGRESDB}
      - PGPORT=5432
    networks:
      - '320'
    container_name: backend-simulator

  backend-editor:
    image: dacollins/docking:backend-editor
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - POSTGRESHOST=${POSTGRESHOST}
      - POSTGRESUSERNAME=${POSTGRESUSERNAME}
      - POSTGRESPASSWORD=${POSTGRESPASSWORD}
      - POSTGRESDB=${POSTGRESDB}
    networks:
      - '320'
    container_name: backend-editor

  database:
    image: postgres
    container_name: postgres-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=db"
    ports:
      - 5432:5432
    expose:
      - '5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - '320'

volumes:
  postgres-data:

networks:
  '320':
