version: "3"
services:
  test-frontend-editor:
    build:
      context: editor/frontend/ethisim
    environment:
      - CI=true
    command: npm test
  test-frontend-simulator:
    build:
      context: simulator/frontend
    environment:
      - CI=true
    command: npm test
  test-frontend-landing-page:
    build:
      context: landing page/welcome-login
    environment:
      - CI=true
    command: npm test