CREATE TABLE "users" (
  "USER_ID" INTEGER PRIMARY KEY,
  "USER_TYPE_ID" INTEGER,
  "EDITOR" BOOLEAN
);

CREATE TABLE "user_types" (
  "USER_TYPE_ID" INTEGER PRIMARY KEY,
  "NAME" TEXT
);

CREATE TABLE "courses" (
  "COURSE_ID" INTEGER PRIMARY KEY,
  "NAME" VARCHAR
);

CREATE TABLE "professors_teach" (
  "USER_ID" INTEGER PRIMARY KEY,
  "COURSE_ID" INTEGER
);

CREATE TABLE "scenarios" (
  "SCENARIO_ID" INTEGER PRIMARY KEY,
  "USER_ID" INTEGER,
  "PUBLIC" BOOLEAN,
  "IS_FINISHED" BOOLEAN,
  "DATE_CREATED" DATE
);

CREATE TABLE "versions" (
  "VERSION_ID" INTEGER PRIMARY KEY,
  "SCENARIO_ID" INTEGER,
  "NAME" VARCHAR,
  "NUM_CONVERSATION" INTEGER,
  "FIRST_PAGE" INTEGER
);

CREATE TABLE "invitations" (
  "INVITATION_KEY" TEXT PRIMARY KEY,
  "VERSION_ID" INTEGER
);

CREATE TABLE "pages" (
  "PAGE_ID" INTEGER PRIMARY KEY,
  "PAGE_TYPE" VARCHAR,
  "PAGE_TITLE" TEXT,
  "VERSION_ID" INTEGER,
  "SCENARIO_ID" INTEGER,
  "BODY" TEXT,
  "NEXT_PAGE" INTEGER,
  "X_COORDINATE" INTEGER,
  "Y_COORDINATE" INTEGER
);

CREATE TABLE "scenarios_for_classes" (
  "SCENARIO_ID" INTEGER,
  "VERSION_ID" INTEGER,
  "COURSE_ID" INTEGER
);

CREATE TABLE "scenarios_for_users" (
  "SCENARIO_ID" INTEGER,
  "VERSION_ID" INTEGER,
  "USER_ID" INTEGER
);

CREATE TABLE "conversations" (
  "CONVERSATION_ID" INTEGER PRIMARY KEY,
  "SCENARIO_ID" INTEGER,
  "STAKEHOLDER_ID" INTEGER,
  "QUESTION" TEXT,
  "RESPONSE_ID" TEXT
);

CREATE TABLE "stakeholders" (
  "STAKEHOLDER_ID" INTEGER PRIMARY KEY,
  "VERSION_ID" INTEGER,
  "SCENARIO_ID" INTEGER,
  "NAME" TEXT,
  "DESCRIPTION" TEXT,
  "JOB" TEXT,
  "INTRODUCTION" TEXT
);

CREATE TABLE "reflection_questions" (
  "id" INTEGER PRIMARY KEY,
  "VERSION_ID" INTEGER,
  "PAGE_ID" INTEGER,
  "REFLECTION_QUESTION" TEXT
);

CREATE TABLE "generic_page" (
  "id" INTEGER PRIMARY KEY,
  "VERSION_ID" INTEGER,
  "PAGE_ID" INTEGER,
  "BODY" TEXT
);

CREATE TABLE "action_page" (
  "id" INTEGER PRIMARY KEY,
  "PAGE_ID" INTEGER,
  "CHOICE" TEXT,
  "RESULT_PAGE" INTEGER
);

CREATE TABLE "issues" (
  "ISSUE_ID" INTEGER PRIMARY KEY,
  "VERSION_ID" INTEGER,
  "SCENARIO_ID" INTEGER,
  "NAME" TEXT,
  "IMPORTANCE_SCORE" INTEGER
);

CREATE TABLE "stakeholder_page" (
  "PAGE_ID" INTEGER PRIMARY KEY,
  "STAKEHOLDER_ID" INTEGER
);

CREATE TABLE "coverage" (
  "STAKEHOLDER_ID" INTEGER PRIMARY KEY,
  "ISSUE_ID" INTEGER,
  "COVERAGE_SCORE" DECIMAL
);

ALTER TABLE "user_types" ADD FOREIGN KEY ("USER_TYPE_ID") REFERENCES "users" ("USER_TYPE_ID");

ALTER TABLE "professors_teach" ADD FOREIGN KEY ("COURSE_ID") REFERENCES "courses" ("COURSE_ID");

ALTER TABLE "users" ADD FOREIGN KEY ("USER_ID") REFERENCES "scenarios" ("USER_ID");

ALTER TABLE "scenarios" ADD FOREIGN KEY ("SCENARIO_ID") REFERENCES "versions" ("SCENARIO_ID");

ALTER TABLE "pages" ADD FOREIGN KEY ("PAGE_ID") REFERENCES "versions" ("FIRST_PAGE");

ALTER TABLE "invitations" ADD FOREIGN KEY ("VERSION_ID") REFERENCES "versions" ("VERSION_ID");

ALTER TABLE "pages" ADD FOREIGN KEY ("NEXT_PAGE") REFERENCES "pages" ("PAGE_ID");

ALTER TABLE "scenarios_for_classes" ADD FOREIGN KEY ("COURSE_ID") REFERENCES "courses" ("COURSE_ID");

ALTER TABLE "scenarios_for_classes" ADD FOREIGN KEY ("SCENARIO_ID") REFERENCES "scenarios" ("SCENARIO_ID");

ALTER TABLE "scenarios_for_classes" ADD FOREIGN KEY ("VERSION_ID") REFERENCES "versions" ("VERSION_ID");

ALTER TABLE "scenarios_for_users" ADD FOREIGN KEY ("SCENARIO_ID") REFERENCES "scenarios" ("SCENARIO_ID");

ALTER TABLE "scenarios_for_users" ADD FOREIGN KEY ("VERSION_ID") REFERENCES "versions" ("VERSION_ID");

ALTER TABLE "scenarios_for_users" ADD FOREIGN KEY ("USER_ID") REFERENCES "users" ("USER_ID");

ALTER TABLE "conversations" ADD FOREIGN KEY ("STAKEHOLDER_ID") REFERENCES "stakeholders" ("STAKEHOLDER_ID");

ALTER TABLE "stakeholders" ADD FOREIGN KEY ("VERSION_ID") REFERENCES "versions" ("VERSION_ID");

ALTER TABLE "reflection_questions" ADD FOREIGN KEY ("PAGE_ID") REFERENCES "pages" ("PAGE_ID");

ALTER TABLE "generic_page" ADD FOREIGN KEY ("PAGE_ID") REFERENCES "pages" ("PAGE_ID");

ALTER TABLE "action_page" ADD FOREIGN KEY ("PAGE_ID") REFERENCES "pages" ("PAGE_ID");

ALTER TABLE "issues" ADD FOREIGN KEY ("VERSION_ID") REFERENCES "versions" ("VERSION_ID");

ALTER TABLE "stakeholder_page" ADD FOREIGN KEY ("PAGE_ID") REFERENCES "pages" ("PAGE_ID");

ALTER TABLE "stakeholder_page" ADD FOREIGN KEY ("STAKEHOLDER_ID") REFERENCES "stakeholders" ("STAKEHOLDER_ID");

ALTER TABLE "stakeholders" ADD FOREIGN KEY ("STAKEHOLDER_ID") REFERENCES "coverage" ("STAKEHOLDER_ID");

ALTER TABLE "coverage" ADD FOREIGN KEY ("ISSUE_ID") REFERENCES "issues" ("ISSUE_ID");
