# Generated by Django 3.1.7 on 2021-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dueDate', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('additional_data', models.CharField(max_length=1000)),
            ],
        ),
    ]
