# Generated by Django 2.2.12 on 2021-04-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPage',
            fields=[
                ('action_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('chosen_choice', models.IntegerField(null=True)),
                ('result_page', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'action_page',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_type', models.CharField(max_length=200)),
                ('page_title', models.CharField(max_length=200)),
                ('version_id', models.IntegerField()),
                ('body', models.TextField()),
                ('next_page', models.IntegerField()),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('public', models.BooleanField()),
                ('is_finished', models.BooleanField()),
                ('date_created', models.DateField()),
            ],
            options={
                'db_table': 'scenario',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('stakeholder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('job', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
            ],
            options={
                'db_table': 'stakeholder',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('num_conversation', models.IntegerField()),
                ('first_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Scenario')),
            ],
            options={
                'db_table': 'version',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('editor', models.BooleanField()),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserType')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='StudentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('date_taken', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'student_time',
            },
        ),
        migrations.CreateModel(
            name='StudentsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
            options={
                'db_table': 'students_in',
            },
        ),
        migrations.CreateModel(
            name='StakeholderPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
                ('stakeholder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Stakeholder')),
            ],
            options={
                'db_table': 'stakeholder_page',
            },
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version'),
        ),
        migrations.CreateModel(
            name='ScenariosFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Scenario')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'scenarios_for',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_taken', models.DateTimeField()),
                ('choice', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'response',
            },
        ),
        migrations.CreateModel(
            name='ReflectionsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflections', models.CharField(max_length=100)),
                ('date_taken', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'reflections_taken',
            },
        ),
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('reflection_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('reflection_question', models.TextField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
            ],
            options={
                'db_table': 'reflection_question',
            },
        ),
        migrations.CreateModel(
            name='ProfessorTeach',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
            options={
                'db_table': 'professor_teach',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('importance_score', models.IntegerField()),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('generic_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page')),
            ],
            options={
                'db_table': 'generic_page',
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_score', models.FloatField()),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Issue')),
                ('stakeholder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Stakeholder')),
            ],
            options={
                'db_table': 'coverage',
            },
        ),
        migrations.CreateModel(
            name='ConversationsHad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('date_taken', models.DateTimeField()),
                ('score', models.FloatField()),
                ('conversation_id', models.IntegerField()),
                ('stakeholder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Stakeholder')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'conversations_had',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_id', models.IntegerField()),
                ('question', models.TextField()),
                ('response_id', models.TextField()),
                ('stakeholder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Stakeholder')),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choices_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.TextField()),
                ('next_page', models.IntegerField()),
                ('action_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ActionPage')),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Version')),
            ],
            options={
                'db_table': 'assigned_to',
            },
        ),
        migrations.AddField(
            model_name='actionpage',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Page'),
        ),
    ]
