# Generated by Django 2.2.12 on 2021-04-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='name',
        ),
    ]
