# Generated by Django 2.2.12 on 2021-05-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='response_id',
            new_name='conversation_response',
        ),
    ]
