# Generated by Django 2.2.12 on 2021-04-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210422_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionpagechoice',
            old_name='chocie',
            new_name='choice',
        ),
    ]
