# Generated by Django 2.2.12 on 2021-04-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210422_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpagechoice',
            name='choice',
            field=models.TextField(null=True),
        ),
    ]
