# Generated by Django 3.1.7 on 2021-03-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_scenarios_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='course_id',
            field=models.ManyToManyField(to='backend.Courses'),
        ),
        migrations.DeleteModel(
            name='StudentsIn',
        ),
    ]
