# Generated by Django 2.2.12 on 2021-04-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210423_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Scenario')),
            ],
            options={
                'db_table': 'class_assignment',
            },
        ),
    ]
