# Generated by Django 3.1.7 on 2021-03-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210327_1745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionpage',
            table='action_page',
        ),
        migrations.AlterModelTable(
            name='actionstaken',
            table='actions_taken',
        ),
        migrations.AlterModelTable(
            name='assignedto',
            table='assigned_to',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='conversation',
        ),
        migrations.AlterModelTable(
            name='conversationshad',
            table='conversations_had',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coverage',
            table='coverage',
        ),
        migrations.AlterModelTable(
            name='genericpage',
            table='generic_page',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issue',
        ),
        migrations.AlterModelTable(
            name='major',
            table='major',
        ),
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
        migrations.AlterModelTable(
            name='professorteach',
            table='professor_teach',
        ),
        migrations.AlterModelTable(
            name='reflectionquestion',
            table='reflection_question',
        ),
        migrations.AlterModelTable(
            name='reflectionstaken',
            table='reflections_taken',
        ),
        migrations.AlterModelTable(
            name='response',
            table='response',
        ),
        migrations.AlterModelTable(
            name='scenario',
            table='scenario',
        ),
        migrations.AlterModelTable(
            name='scenariosfor',
            table='scenarios_for',
        ),
        migrations.AlterModelTable(
            name='stakeholder',
            table='stakeholder',
        ),
        migrations.AlterModelTable(
            name='stakeholderpage',
            table='stakeholder_page',
        ),
        migrations.AlterModelTable(
            name='studentsin',
            table='students_in',
        ),
        migrations.AlterModelTable(
            name='studenttime',
            table='student_time',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='user_type',
        ),
        migrations.AlterModelTable(
            name='version',
            table='version',
        ),
    ]
