# Generated by Django 2.2.12 on 2021-04-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210327_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('next_page', models.IntegerField()),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.RenameField(
            model_name='actionpage',
            old_name='choice',
            new_name='chosen_choice',
        ),
        migrations.DeleteModel(
            name='ActionsTaken',
        ),
        migrations.AddField(
            model_name='choice',
            name='action_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ActionPage'),
        ),
    ]
