# Generated by Django 3.2 on 2021-04-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210327_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_started', models.DateTimeField()),
                ('is_finished', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.RenameModel(
            old_name='ScenariosFor',
            new_name='ScenariosForUser',
        ),
        migrations.RenameField(
            model_name='actionpage',
            old_name='action_page_id',
            new_name='ap_id',
        ),
        migrations.RenameField(
            model_name='actionpage',
            old_name='choice',
            new_name='choices',
        ),
        migrations.RenameField(
            model_name='actionstaken',
            old_name='action_page',
            new_name='ap_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='scenario_id',
        ),
        migrations.RemoveField(
            model_name='conversationshad',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='page',
            name='version_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='name',
        ),
        migrations.AddField(
            model_name='issue',
            name='scenario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='scenario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='scenario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.scenario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionstaken',
            name='response_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.response'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='response_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.response'),
        ),
        migrations.AlterField(
            model_name='conversationshad',
            name='conversation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.conversation'),
        ),
        migrations.AlterField(
            model_name='reflectionstaken',
            name='reflections',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='job',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='scenariosforuser',
            table='scenarios_for_user',
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.page')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.session')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.version')),
            ],
            options={
                'db_table': 'session_time',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='scenario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.scenario'),
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AddField(
            model_name='session',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.version'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_key', models.TextField(primary_key=True, serialize=False)),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.version')),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.actionpage')),
                ('next_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.page')),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_changed', models.CharField(max_length=100)),
                ('new_content', models.TextField()),
                ('forked_form', models.IntegerField()),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.version')),
            ],
            options={
                'db_table': 'change',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('actionpage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.version')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.AddField(
            model_name='conversationshad',
            name='session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflectionstaken',
            name='session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.session'),
            preserve_default=False,
        ),
    ]
