# Generated by Django 3.2 on 2021-04-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210410_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionpage',
            old_name='page_id',
            new_name='page',
        ),
    ]
