# Generated by Django 2.2.12 on 2021-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_reflectionstaken_rq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='most_recent_access',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
