# Generated by Django 3.2 on 2021-04-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_page_id_actionpage_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionpage',
            old_name='page',
            new_name='page_id',
        ),
    ]
