# Generated by Django 3.2.4 on 2021-06-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_ID', models.IntegerField()),
                ('NAME', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('SESSION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_ID', models.IntegerField()),
                ('SCENARIO_ID', models.IntegerField()),
                ('DATE_STARTED', models.DateTimeField()),
                ('DATE_FINISHED', models.DateTimeField()),
                ('IS_FINISHED', models.BooleanField(default=False)),
                ('MOST_RECENT_ACCESS', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('USER_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('AFFILIATION', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.courses')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.users')),
            ],
        ),
        migrations.CreateModel(
            name='session_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_TAKEN', models.DateTimeField()),
                ('PAGE_ID', models.IntegerField()),
                ('START_TIME', models.DateTimeField()),
                ('END_TIME', models.DateTimeField()),
                ('SESSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='reflections_taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFLECTIONS', models.TextField()),
                ('RQ_ID', models.IntegerField()),
                ('PAGE_ID', models.IntegerField()),
                ('DATE_TAKEN', models.DateTimeField()),
                ('SESSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='course_onvitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCESS_KEY', models.IntegerField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.courses')),
            ],
        ),
        migrations.CreateModel(
            name='course_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCENARIO_ID', models.IntegerField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.courses')),
            ],
        ),
        migrations.CreateModel(
            name='conversations_had',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_TAKEN', models.DateTimeField()),
                ('STAKEHOLDER_ID', models.IntegerField()),
                ('SESSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='action_page_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APC_ID', models.IntegerField()),
                ('PAGE_ID', models.IntegerField()),
                ('DATE_TAKEN', models.DateTimeField()),
                ('SESSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sessions')),
            ],
        ),
    ]
