# Generated by Django 3.2.4 on 2021-06-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_onvitations',
            new_name='course_invitations',
        ),
    ]
