# Generated by Django 2.2.12 on 2021-06-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='COURSE',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
