# Generated by Django 2.2.12 on 2021-06-17 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210616_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='user',
            field=models.ForeignKey(default='phaas', on_delete=django.db.models.deletion.CASCADE, to='tables.Users'),
        ),
    ]
