# Generated by Django 2.2.12 on 2021-06-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210617_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', default='phaas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_creator2', to='tables.Users'),
        ),
    ]
