# Generated by Django 2.2.12 on 2021-06-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210617_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations_had',
            name='STAKEHOLDER_ID',
            field=models.ForeignKey(db_column='STAKEHOLDER', on_delete=django.db.models.deletion.CASCADE, to='tables.stakeholders'),
        ),
    ]
