# Generated by Django 2.2.12 on 2021-06-06 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210604_2156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action_page_choices',
            unique_together={('SESSION_ID', 'APC_ID')},
        ),
        migrations.AlterUniqueTogether(
            name='conversations_had',
            unique_together={('SESSION_ID', 'STAKEHOLDER_ID')},
        ),
        migrations.AlterUniqueTogether(
            name='reflections_taken',
            unique_together={('SESSION_ID', 'RQ_ID')},
        ),
    ]
