# Generated by Django 2.2.12 on 2021-06-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20210621_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations_had',
            name='STAKEHOLDER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stakeholders'),
        ),
    ]
