# Generated by Django 2.2.12 on 2021-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20210606_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_times',
            name='DATE_TAKEN',
            field=models.DateTimeField(null=True),
        ),
    ]
