# Generated by Django 2.2.12 on 2021-06-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210607_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_times',
            name='END_TIME',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session_times',
            name='START_TIME',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='DATE_FINISHED',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='DATE_STARTED',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='MOST_RECENT_ACCESS',
            field=models.DateTimeField(),
        ),
    ]
