# Generated by Django 2.2.12 on 2021-06-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210622_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(db_column='token', unique=True)),
                ('user', models.CharField(db_column='user', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorWhitelist',
            fields=[
                ('email', models.EmailField(db_column='Email', max_length=225, unique=True)),
                ('netId', models.CharField(db_column='NetId', max_length=150, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user_access',
            name='SHARED_BY',
            field=models.ForeignKey(default='phaas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access2', to='tables.Users'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='PAGE_TYPE',
            field=models.CharField(choices=[('I', 'INTRO'), ('G', 'GENERIC'), ('R', 'REFLECTION'), ('S', 'STAKEHOLDER'), ('A', 'ACTION'), ('F', 'FEEDBACK')], max_length=2),
        ),
    ]
