# Generated by Django 2.2.12 on 2021-06-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210608_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_times',
            old_name='DATE_TAKEN',
            new_name='MOST_RECENT_ACCESS',
        ),
    ]
