# Generated by Django 2.2.12 on 2021-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20210611_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='COURSE_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
