# Generated by Django 2.2.12 on 2021-06-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20210614_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('USER_ID', 'COURSE_ID')},
        ),
    ]
