from django.contrib import admin

# Register your models here.
from backend.models import *

admin.site.register(UserTypes)
admin.site.register(Users)
admin.site.register(Courses)
admin.site.register(StudentsIn)
admin.site.register(Majors)
admin.site.register(ProfessorTeach)
admin.site.register(Scenarios)
admin.site.register(Pages)
admin.site.register(Versions)
admin.site.register(Responses)
admin.site.register(AssignedTo)
admin.site.register(ScenariosFor)
admin.site.register(Stakeholders)
admin.site.register(ConversationsHad)
# admin.site.register(Conversations)
admin.site.register(ReflectionQuestions)
admin.site.register(Conversations)
admin.site.register(GenericPage)
admin.site.register(ActionPage)
admin.site.register(ActionsTaken)
admin.site.register(Issues)
admin.site.register(StakeholderPage)
admin.site.register(Coverage)
admin.site.register(ReflectionsTaken)
admin.site.register(StudentTimes)