# # pull official base image
FROM node:13.12.0-alpine as build

# # set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

ENV REACT_APP_URL=https://ethisim1.cs.umass.edu

RUN npm run build