# Generated by Django 2.2.20 on 2021-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='SUMMARY',
            field=models.TextField(default='', null=True),
        ),
    ]
