# Generated by Django 2.2.20 on 2021-05-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='NUM_CONVERSATION',
            field=models.IntegerField(blank=True, db_column='NUM_CONVERSATION', null=True),
        ),
    ]
