# Generated by Django 2.2.12 on 2021-04-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210407_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='ISSUE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage1', to='tables.Issues'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='STAKEHOLDER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage2', to='tables.stakeholders'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='SCENARIO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_id5', to='tables.scenarios'),
        ),
        migrations.AlterUniqueTogether(
            name='scenarios',
            unique_together=set([('SCENARIO' ,"VERSION")]),
        ),
        migrations.RemoveField(
            model_name='scenarios',
            name='VERSION',
        ),
    ]
