# Generated by Django 2.2.20 on 2021-06-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_scenarios_num_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCESS_LEVEL', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='scenarios',
            old_name='user',
            new_name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.AddField(
            model_name='users',
            name='AFFILIATION',
            field=models.CharField(default='Professor', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='EMAIL',
            field=models.EmailField(default='phaas@cs.umass.edu', max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='NAME',
            field=models.CharField(default='Peter Haas', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='USER_ID',
            field=models.CharField(default='phaas', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserTypes',
        ),
        migrations.AddField(
            model_name='user_access',
            name='SCENARIO_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access1', to='tables.scenarios'),
        ),
        migrations.AddField(
            model_name='user_access',
            name='USER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access1', to='tables.Users'),
        ),
    ]
