# Generated by Django 2.2.20 on 2021-06-05 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210605_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='USER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_user', to='tables.Users'),
        ),
    ]
