# Generated by Django 2.2.12 on 2021-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210607_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorWhitelist',
            fields=[
                ('email', models.EmailField(db_column='Email', max_length=225, primary_key=True, serialize=False)),
                ('netId', models.CharField(db_column='NetId', max_length=150, unique=True)),
            ],
        ),
    ]
