# Generated by Django 2.2.12 on 2021-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_action_page_responses_conversations_had_course_assignment_course_invitations_reflections_taken_sessi'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(db_column='token', unique=True)),
                ('user', models.CharField(db_column='user', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorWhitelist',
            fields=[
                ('email', models.EmailField(db_column='Email', max_length=225, unique=True)),
                ('netId', models.CharField(db_column='NetId', max_length=150, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='COURSE',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
