# Generated by Django 2.2.12 on 2021-06-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20210617_2126'),
        ('tables', '0004_editorwhitelist'),
    ]

    operations = [
    ]
