# Generated by Django 2.2.20 on 2021-06-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20210626_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_access',
            name='SHARED_BY',
            field=models.ForeignKey(default='phaas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access2', to='tables.Users'),
        ),
    ]
