# Generated by Django 2.2.20 on 2021-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_user_access_shared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='PAGE_TYPE',
            field=models.CharField(choices=[('I', 'INTRO'), ('G', 'GENERIC'), ('R', 'REFLECTION'), ('S', 'STAKEHOLDER'), ('A', 'ACTION'), ('F', 'FEEDBACK')], max_length=2),
        ),
    ]
