# Generated by Django 2.2.20 on 2021-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210629_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='DEMO_MODE',
            field=models.BooleanField(default=False),
        ),
    ]
