# Generated by Django 2.2.12 on 2021-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210629_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_invitations',
            name='ACCESS_KEY',
            field=models.CharField(max_length=6),
        ),
    ]
