name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds the three docker containers and pushes them to docker hub
  build-docker-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
          
      - name: build and push editor frontend
        uses: docker/build-push-action@v2
        with:
          context: ./editor/frontend/ethisim/
          push: true
          tags: dacollins/docking:frontend-editor
          cache-from: type=registery, ref=dacollins/ethisim:frontend-editor
          cache-to: type=inline
          
      - name: build and push editor backend
        uses: docker/build-push-action@v2
        with:
          context: ./editor/backend/
          push: true
          tags: dacollins/docking:backend-editor
          cache-from: type=registery, ref=dacollins/ethisim:backend-editor
          cache-to: type=inline
          
      - name: build and push simulator frontend
        uses: docker/build-push-action@v2
        with:
          context: ./simulator/frontend/
          push: true
          tags: dacollins/docking:frontend-simulator
          cache-from: type=registery, ref=dacollins/ethisim:frontend-simulator
          cache-to: type=inline
          
      - name: build and push simulator backend
        uses: docker/build-push-action@v2
        with:
          context: ./simulator/goon-universe/
          push: true
          tags: dacollins/docking:backend-simulator
          cache-from: type=registery, ref=dacollins/ethisim:backend-simulator
          cache-to: type=inline
          
      - name: build and push landing page
        uses: docker/build-push-action@v2
        with:
          context: ./landing page/welcome-login/
          push: true
          tags: dacollins/docking:frontend-landing-page
          cache-from: type=registery, ref=dacollins/ethisim:frontend-landing-page
          cache-to: type=inline
      
